# Generated by Django 4.2.26 on 2025-11-29 06:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issue_tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('bug', 'Bug'), ('feature', 'Feature Request'), ('question', 'Question'), ('enhancement', 'Enhancement'), ('documentation', 'Documentation'), ('task', 'Task')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('template_content', models.TextField(help_text='Template for issue description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('assigned', 'Assigned to Issue'), ('mentioned', 'Mentioned in Comment'), ('status_change', 'Issue Status Changed'), ('new_comment', 'New Comment'), ('issue_updated', 'Issue Updated')], max_length=50)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('filter_params', models.JSONField(help_text='Stored filter parameters')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('notification_enabled', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='issue',
            name='issue_track_assigne_d3b6e3_idx',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='new_value',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='old_value',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='attachment',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='attachment',
            name='file_size',
            field=models.PositiveIntegerField(default=0, help_text='File size in bytes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='is_internal',
            field=models.BooleanField(default=False, help_text='Internal comment, not visible to reporters'),
        ),
        migrations.AddField(
            model_name='issue',
            name='actual_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='ai_confidence',
            field=models.FloatField(blank=True, help_text='AI confidence score 0-1', null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='ai_suggested_category',
            field=models.CharField(blank=True, choices=[('bug', 'Bug'), ('feature', 'Feature Request'), ('question', 'Question'), ('enhancement', 'Enhancement'), ('documentation', 'Documentation'), ('task', 'Task')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='issue_tracker_app.issue'),
        ),
        migrations.AddField(
            model_name='issue',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='parent_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_issues', to='issue_tracker_app.issue'),
        ),
        migrations.AddField(
            model_name='issue',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='issue',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='issue',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watched_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='label',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='label',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('commented', 'Commented'), ('status_changed', 'Status Changed'), ('priority_changed', 'Priority Changed'), ('assigned', 'Assigned'), ('unassigned', 'Unassigned'), ('labeled', 'Labeled'), ('unlabeled', 'Unlabeled'), ('attached', 'Attached File'), ('closed', 'Closed'), ('reopened', 'Reopened')], max_length=50),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='attachments/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'txt', 'jpg', 'jpeg', 'png', 'gif', 'zip', 'rar'])]),
        ),
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('bug', 'Bug'), ('feature', 'Feature Request'), ('question', 'Question'), ('enhancement', 'Enhancement'), ('documentation', 'Documentation'), ('task', 'Task')], db_index=True, default='bug', max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('reopened', 'Reopened')], db_index=True, default='open', max_length=20),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['assignee', 'status'], name='issue_track_assigne_bac59a_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['reporter'], name='issue_track_reporte_1b73d5_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['category'], name='issue_track_categor_2b4e16_idx'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedfilter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_filters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issue_tracker_app.issue'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issuetemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
